org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=26.1
minecraft_version_range=[26.1]
neo_version=26.1.0.19-beta
loader_version_range=[1,)
parchment_minecraft_version=26.1
parchment_mappings_version=none

mod_id=rankboard
mod_name=RankBoard
mod_license=MIT
mod_version=1.9.1
mod_group_id=cn.bamgdam
